name: srs-llm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - transformers>=4.41.1
  - pytorch
  - pytorch-cuda=12.1
  - accelerate
  - jinja2
  - networkx
  - pydot
  - pypdf2
  - pip
