name: srs-llm
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - transformers
  - pytorch
  # Comment below out if you don't have a GPU or nvidia drivers and being finicky.
  - pytorch-cuda=12.1
  - jinja2
  - networkx
  - pydot
  - requests
  - pypdf2
  - markdown
  - beautifulsoup4
  - pip
