name: srs-llm
channels:
  - huggingface
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - transformers
  - networkx
  - pydot
  - requests
  - pypdf2
  - markdown
  - beautifulsoup4
  - pip
